#!/bin/bash

post_install() {
    _binDir="/usr/share/webapps/kopano-webapp"
    _confDir="/etc/webapps/kopano-webapp"

    install --backup=simple --suffix .pacsave -o http -g http -m 0660 \
	${_binDir}/config.php.dist
	${_confDir}/config.php

    install --backup=simple --suffix .pacsave -o http -g http -m 0660 \
	${_binDir}/debug.php.dist
	${_confDir}/debug.php

    return 0
}


